### ISSUE TITLE
Citações no decorrer do texto ultrapassam a margem

### ISSUE THREAD

**Issue by marcelomarinho** [yguarata/risethesis#1]
Por algum motivo as citações estão ultrapassado a margem da folha. Não ocorre em todas as citações próximas do final da linha. Coloquei uma imagem em anexo. Poderias me ajudar?

![exemplo](https://cloud.githubusercontent.com/assets/13456166/8833531/9ae9adea-3085-11e5-9fef-f755adcbcda2.jpg)

Obrigado, Marcelo

**Comment by yguarata** [comment]
Olá Marcelo,

já tentou utilizar \usepackage{breakurl}?

[]s

**Comment by marcelomarinho** [comment]
Olá Yguarata,
Tentei, porém ainda assim permanece ultrapassando. 
[]s

**Comment by yguarata** [comment]
Marcelo,

tenta desabilitar o pacote hyperref. É esse pacote que insere os links nas referências. Se resolver, aí temos que investigar como fazer essa quebra de linha automaticamente com o hyperref.

[]s

**Comment by marcelomarinho** [comment]
Oi Yguarata,

De fato! Quando desabilitei o pacote hyperref a quebra de linhas funcionou! Só perdi os links para as referências, mas isso é o de menos. Caso encontre alguma forma de adicionar o link e quebrar as linhas, posto aqui!

Muito obrigado pela ajuda!

Abraços,

Marcelo
