### ISSUE TITLE
risethesis-master/risethesis.cls, line 101  LaTeX Error: File `psboxit.sty' not found.

### ISSUE THREAD

**Issue by acesso** [yguarata/risethesis#2]
Ola ,

Me deparei com este erro qunado enviei o zip do rise para o sharelatex:

LaTeX Error: File `psboxit.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.101 \RequirePackage
                     [avantgarde]{quotchap}^^M
**\* (cannot \read from terminal in nonstop modes)

 Segui adicionado o arquivo indicado no erro que entrei  em https://www.ctan.org/pkg/psboxit?lang=en

Aparentemente resolveu, talves seja interessante adicionar o arquivo no repo.

**Comment by jfsc** [comment]
No fedora21, 
fiz o seguitne 

> mkdir /usr/share/texlive/texmf-dist/tex/latex/psboxit 
> wget -O psboxit.sty https://www.ctan.org/tex-archive/macros/latex209/contrib/misc/psboxit.sty 
> mktexlsr

**Comment by acesso** [comment]
funciona no latex na maquina, mas pelo sharelatex (que usa o livetex no servidor) o problema não pode ser resolvido da mesma forma. A solucao que fiz foi compativel com o sharelatex(online)

**Comment by zimmerle** [comment]
So para efeito de ficar registrado uma possivel solucao, voce pode copiar o psboxit.sty para a raiz do repositorio.

```
$ cd /path/to/your/repo
$ wget https://www.ctan.org/tex-archive/macros/latex209/contrib/misc/psboxit.sty 
$ make
```
