### ISSUE TITLE
Ajustes na citação

### ISSUE THREAD

**Issue by adrielcafe** [yguarata/risethesis#6]
Olá pessoal!
A bibliotecária do CCEN, Monick Raquel, pediu para a seguinte alteração ser feita nas citações diretas em minha dissertação:

> Quando houver citações diretamente no texto, sem ser entre parêntesis, os nomes dos autores nesse tipo de citação devem ficar em minúsculo e não são separados por ponto e vírgula como nas citações entre parêntesis. Se houver 2 autores eles separam-se pela letra "e", e se houver 3 autores coloca-se uma vírgula entre o primeiro e o segundo e a letra "e" entre o segundo e o terceiro.

Ex 1:

```
... em um artigo publicado por BERNERS-LEE; HENDLER; LASSILA (2001). 

deve ficar:

... em um artigo publicado por Berners-Lee, Hendler e Lassila (2001).
```

Ex 2:

```
Segundo BREITMAN (2005)...

deve ficar:

Segundo Breitman (2005)...
```

Tentei realizar essas mudanças de várias formas (em `abnt.bst`, `natbib.sty` e `risethesis.cls`), mas não tive sucesso. A única solução que encontrei foi substituir o risethesis pelo [abntex2](https://github.com/abntex/abntex2), só que assim perco toda a formatação 😞 

Vocês tem alguma ideia de como posso conseguir fazer esta alteração nas citações? Alguma dica @FilipeSantana?

Valeu!

**Comment by FilipeSantana** [comment]
Eu estive pensando em como fazer esta alteração em específico. 
Na minha cabeça, há duas soluções possíveis:
1) alterar o código do abnt.bst diretamente;
2) aderir completamente ao abntex2;

Irei verificar se é possível fazer no primeiro, importando conteúdo do segundo.
Todavia, o abntex2 é o mais correto. Mas há diferenças na forma de criar citação e em alguns outros parâmetros pequenos. Nada impossível, mas é diferente do LaTeX puro (que eu gosto de utilizar) ou de pacotes mais clássicos como o natbib por exemplo.

Vi que o pessoal do abntex2 estava criando um modelo abntex3, mas perdi o fio da meada a pouco tempo. Possivelmente, devo fazer a conversão da minha tese pacote por pacote para facilitar rastrear problemas. Fora isso, não faço nem ideia de como proceder.

Talves isso possa ser uma solução: https://github.com/dudektria/biblatex-abnt

Mas não tenho como testar agora.

**Comment by adrielcafe** [comment]
Valeu pelas dicas @FilipeSantana !
Em breve posto o resultado.
